### ISSUE TITLE
Example doesn't work / Plans for categorical data?

### ISSUE THREAD

**Issue by fleicher** [RektPunk/MQBoost#25]
Hey, I am trying to run the examples.

But when I am executing mqoptimizer.py, I get the error that the parameter epsilon when creating the object MQObjective is not set. A default value should solve the problem.

```
mq_optimizer.optimize_params(
    dataset=train_dataset,
    n_trials=10,
)
```

Also, one question, do you have any plans to natively support categorical data (at least for LightGBM)?

Thank you for your work

**Comment by RektPunk** [comment]
Hey, @fleicher. Thank you so, so much for letting me know. You are literally my lifesaver!
My response is a bit late, but I fixed it quickly as soon as I checked! :) 
BTW, could you explain a bit more what you mean by 'natively support categorical data' at the end?

**Comment by RektPunk** [comment]
Hey @fleicher, I'm working on 'support categorical data' at https://github.com/RektPunk/MQBoost/pull/32. Hope it is what you expected.
