### ISSUE TITLE
Feature Request: Support for sample weights/ Weight data

### ISSUE THREAD

**Issue by rhythm-saparia** [RektPunk/MQBoost#45]
Hi, Thank you for the great work on MQBoost! I have a feature request that could improve the library's flexibility and is required for one of my use cases:

**Support for Sample Weights/ Weight Data**: It would be helpful to allow passing weights/ data weights to the model (like for example how we pass `sample_weight` to lightgbm fit method), which can be useful for giving certain samples more emphasis.

I believe these additions would significantly enhance MQBoost's usability and flexibility. Please let me know if further details are needed.

Thanks!

**Comment by RektPunk** [comment]
Hey, @rhythm-saparia. It's definitely possible, and I'll go ahead and try to implement it. Thank you so much for bringing up this request. I really appreciate the feedback and the opportunity to improve MQBoost.

**Comment by RektPunk** [comment]
Now, you can use weight in `MQDataset`. For example, 
```
train_dataset = MQDataset(data=x, label=y, alphas=alphas, weight=weight)
```
