### ISSUE TITLE
Issue: weights not being considered during training

### ISSUE THREAD

**Issue by rhythm-saparia** [RektPunk/MQBoost#48]
When passing varying sample weights to MQDataset and training with MQRegressor, the predictions remain the same irrespective of the weights. I verified that the weights are correctly generated and passed to MQDataset. However, this does not impact the model’s output as expected.

Environment
MQBoost Version: 0.2.9
Python Version: 3.11.2

Here is a minimal example that reproduces the issue:

```
import numpy as np
import pandas as pd
from mqboost import MQDataset, MQRegressor

np.random.seed(42)

n_samples = 100
data = pd.DataFrame({
    "feature1": np.random.rand(n_samples),
    "feature2": np.random.rand(n_samples),
})
labels = pd.Series(np.random.rand(n_samples), name="target")

uniform_weights = pd.Series(1.0, index=data.index)
decayed_weights = pd.Series(np.exp(-0.1 * np.arange(n_samples)), index=data.index)

dataset_uniform = MQDataset(data=data[["feature1", "feature2"]], label=labels, alphas=[0.2, 0.5, 0.8], model="lightgbm", weight=uniform_weights)
model_uniform = MQRegressor(params={}, model="lightgbm")
model_uniform.fit(dataset_uniform)
predictions_uniform = model_uniform.predict(dataset_uniform)

dataset_decayed = MQDataset(data=data[["feature1", "feature2"]], label=labels, alphas=[0.2, 0.5, 0.8], model="lightgbm", weight=decayed_weights)
model_decayed = MQRegressor(params={}, model="lightgbm")
model_decayed.fit(dataset_decayed)
predictions_decayed = model_decayed.predict(dataset_decayed)

print("Predictions with uniform weights:\n", predictions_uniform[:10])
print("Predictions with decayed weights:\n", predictions_decayed[:10])

```

It'll be a great help if this issue gets resolved 😄

**Comment by RektPunk** [comment]
Well, it looks like the weight doesn't affect the custom objective. Thanks for raising the issue @rhythm-saparia —I'll look into it more closely.

**Comment by RektPunk** [comment]
Hey @rhythm-saparia, can you try it once again? It's on version `0.2.10`

**Comment by rhythm-saparia** [comment]
It seems to be working now @RektPunk ,thank you!

**Comment by RektPunk** [comment]
Thanks, for any another suggestion, just let me know :) I'll close this issue.
